/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedBillingImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedLayoutImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutIndexImport } from './routes/_authenticated/_layout/index'
import { Route as AuthenticatedInviteInviteCodeImport } from './routes/_authenticated/invite.$inviteCode'
import { Route as AuthenticatedAccessTokenTokenImport } from './routes/_authenticated/access-token.$token'
import { Route as AuthenticatedLayoutMyProfileImport } from './routes/_authenticated/_layout/my-profile'
import { Route as AuthenticatedLayoutMyProfileIndexImport } from './routes/_authenticated/_layout/my-profile/index'
import { Route as AuthenticatedDevicesLinkTokenImport } from './routes/_authenticated/devices.link.$token'
import { Route as AuthenticatedLayoutTeamsGroupIdImport } from './routes/_authenticated/_layout/teams/$groupId'
import { Route as AuthenticatedLayoutMyProfileFeaturesImport } from './routes/_authenticated/_layout/my-profile/features'
import { Route as AuthenticatedLayoutGamesGameIdImport } from './routes/_authenticated/_layout/games/$gameId'
import { Route as AuthenticatedLayoutTeamsGroupIdIndexImport } from './routes/_authenticated/_layout/teams/$groupId/index'
import { Route as AuthenticatedLayoutGamesGameIdIndexImport } from './routes/_authenticated/_layout/games/$gameId/index'
import { Route as AuthenticatedLayoutTeamsGroupIdSettingsImport } from './routes/_authenticated/_layout/teams/$groupId/settings'
import { Route as AuthenticatedLayoutTeamsGroupIdMembersImport } from './routes/_authenticated/_layout/teams/$groupId/members'
import { Route as AuthenticatedLayoutTeamsGroupIdBillingImport } from './routes/_authenticated/_layout/teams/$groupId/billing'
import { Route as AuthenticatedLayoutGamesGameIdTokensImport } from './routes/_authenticated/_layout/games/$gameId/tokens'
import { Route as AuthenticatedLayoutGamesGameIdSettingsImport } from './routes/_authenticated/_layout/games/$gameId/settings'
import { Route as AuthenticatedLayoutGamesGameIdBillingImport } from './routes/_authenticated/_layout/games/$gameId/billing'
import { Route as AuthenticatedLayoutTeamsGroupIdSettingsIndexImport } from './routes/_authenticated/_layout/teams/$groupId/settings/index'
import { Route as AuthenticatedLayoutGamesGameIdSettingsIndexImport } from './routes/_authenticated/_layout/games/$gameId/settings/index'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId'
import { Route as AuthenticatedLayoutGamesGameIdSettingsTokensImport } from './routes/_authenticated/_layout/games/$gameId/settings/tokens'
import { Route as AuthenticatedLayoutGamesGameIdNamespacesSplatImport } from './routes/_authenticated/_layout/games/$gameId/namespaces/$'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdIndexImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/index'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdVersionsImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/versions'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdTokensImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/tokens'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdMatchmakerImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/matchmaker'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdCdnImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/cdn'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersIndexImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/index'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesIndexImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/index'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendIndexImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/index'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersBuildsImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/builds'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesSettingsImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/settings'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesLogsImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/logs'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendVariablesImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/variables'
import { Route as AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendLogsImport } from './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/logs'

// Create Virtual Routes

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdModulesLazyImport =
  createFileRoute(
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/modules',
  )()

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedBillingRoute = AuthenticatedBillingImport.update({
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLayoutRoute = AuthenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedLayoutIndexRoute = AuthenticatedLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

const AuthenticatedInviteInviteCodeRoute =
  AuthenticatedInviteInviteCodeImport.update({
    path: '/invite/$inviteCode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAccessTokenTokenRoute =
  AuthenticatedAccessTokenTokenImport.update({
    path: '/access-token/$token',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedLayoutMyProfileRoute =
  AuthenticatedLayoutMyProfileImport.update({
    path: '/my-profile',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutMyProfileIndexRoute =
  AuthenticatedLayoutMyProfileIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedLayoutMyProfileRoute,
  } as any)

const AuthenticatedDevicesLinkTokenRoute =
  AuthenticatedDevicesLinkTokenImport.update({
    path: '/devices/link/$token',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedLayoutTeamsGroupIdRoute =
  AuthenticatedLayoutTeamsGroupIdImport.update({
    path: '/teams/$groupId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutMyProfileFeaturesRoute =
  AuthenticatedLayoutMyProfileFeaturesImport.update({
    path: '/features',
    getParentRoute: () => AuthenticatedLayoutMyProfileRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdRoute =
  AuthenticatedLayoutGamesGameIdImport.update({
    path: '/games/$gameId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutTeamsGroupIdIndexRoute =
  AuthenticatedLayoutTeamsGroupIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedLayoutTeamsGroupIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdIndexRoute =
  AuthenticatedLayoutGamesGameIdIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdRoute,
  } as any)

const AuthenticatedLayoutTeamsGroupIdSettingsRoute =
  AuthenticatedLayoutTeamsGroupIdSettingsImport.update({
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutTeamsGroupIdRoute,
  } as any)

const AuthenticatedLayoutTeamsGroupIdMembersRoute =
  AuthenticatedLayoutTeamsGroupIdMembersImport.update({
    path: '/members',
    getParentRoute: () => AuthenticatedLayoutTeamsGroupIdRoute,
  } as any)

const AuthenticatedLayoutTeamsGroupIdBillingRoute =
  AuthenticatedLayoutTeamsGroupIdBillingImport.update({
    path: '/billing',
    getParentRoute: () => AuthenticatedLayoutTeamsGroupIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdTokensRoute =
  AuthenticatedLayoutGamesGameIdTokensImport.update({
    path: '/tokens',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdSettingsRoute =
  AuthenticatedLayoutGamesGameIdSettingsImport.update({
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdBillingRoute =
  AuthenticatedLayoutGamesGameIdBillingImport.update({
    path: '/billing',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdRoute,
  } as any)

const AuthenticatedLayoutTeamsGroupIdSettingsIndexRoute =
  AuthenticatedLayoutTeamsGroupIdSettingsIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedLayoutTeamsGroupIdSettingsRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdSettingsIndexRoute =
  AuthenticatedLayoutGamesGameIdSettingsIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdSettingsRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport.update({
    path: '/games/$gameId/environments/$namespaceId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdSettingsTokensRoute =
  AuthenticatedLayoutGamesGameIdSettingsTokensImport.update({
    path: '/tokens',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdSettingsRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdNamespacesSplatRoute =
  AuthenticatedLayoutGamesGameIdNamespacesSplatImport.update({
    path: '/namespaces/$',
    getParentRoute: () => AuthenticatedLayoutGamesGameIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdIndexRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdIndexImport.update({
    path: '/',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdModulesLazyRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdModulesLazyImport.update(
    {
      path: '/modules',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
    } as any,
  ).lazy(() =>
    import(
      './routes/_authenticated/_layout/games/$gameId_/environments/$namespaceId/modules.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdVersionsRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdVersionsImport.update({
    path: '/versions',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdTokensRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdTokensImport.update({
    path: '/tokens',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersImport.update({
    path: '/servers',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdMatchmakerRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdMatchmakerImport.update({
    path: '/matchmaker',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesImport.update({
    path: '/lobbies',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdCdnRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdCdnImport.update({
    path: '/cdn',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendImport.update({
    path: '/backend',
    getParentRoute: () =>
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute,
  } as any)

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersIndexRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesIndexRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendIndexRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendIndexImport.update(
    {
      path: '/',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersBuildsRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersBuildsImport.update(
    {
      path: '/builds',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesSettingsRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesSettingsImport.update(
    {
      path: '/settings',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesLogsRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesLogsImport.update(
    {
      path: '/logs',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendVariablesRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendVariablesImport.update(
    {
      path: '/variables',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendRoute,
    } as any,
  )

const AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendLogsRoute =
  AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendLogsImport.update(
    {
      path: '/logs',
      getParentRoute: () =>
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_layout/my-profile': {
      id: '/_authenticated/_layout/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AuthenticatedLayoutMyProfileImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/access-token/$token': {
      id: '/_authenticated/access-token/$token'
      path: '/access-token/$token'
      fullPath: '/access-token/$token'
      preLoaderRoute: typeof AuthenticatedAccessTokenTokenImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invite/$inviteCode': {
      id: '/_authenticated/invite/$inviteCode'
      path: '/invite/$inviteCode'
      fullPath: '/invite/$inviteCode'
      preLoaderRoute: typeof AuthenticatedInviteInviteCodeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/games/$gameId': {
      id: '/_authenticated/_layout/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/my-profile/features': {
      id: '/_authenticated/_layout/my-profile/features'
      path: '/features'
      fullPath: '/my-profile/features'
      preLoaderRoute: typeof AuthenticatedLayoutMyProfileFeaturesImport
      parentRoute: typeof AuthenticatedLayoutMyProfileImport
    }
    '/_authenticated/_layout/teams/$groupId': {
      id: '/_authenticated/_layout/teams/$groupId'
      path: '/teams/$groupId'
      fullPath: '/teams/$groupId'
      preLoaderRoute: typeof AuthenticatedLayoutTeamsGroupIdImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/devices/link/$token': {
      id: '/_authenticated/devices/link/$token'
      path: '/devices/link/$token'
      fullPath: '/devices/link/$token'
      preLoaderRoute: typeof AuthenticatedDevicesLinkTokenImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/_layout/my-profile/': {
      id: '/_authenticated/_layout/my-profile/'
      path: '/'
      fullPath: '/my-profile/'
      preLoaderRoute: typeof AuthenticatedLayoutMyProfileIndexImport
      parentRoute: typeof AuthenticatedLayoutMyProfileImport
    }
    '/_authenticated/_layout/games/$gameId/billing': {
      id: '/_authenticated/_layout/games/$gameId/billing'
      path: '/billing'
      fullPath: '/games/$gameId/billing'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdBillingImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdImport
    }
    '/_authenticated/_layout/games/$gameId/settings': {
      id: '/_authenticated/_layout/games/$gameId/settings'
      path: '/settings'
      fullPath: '/games/$gameId/settings'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdSettingsImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdImport
    }
    '/_authenticated/_layout/games/$gameId/tokens': {
      id: '/_authenticated/_layout/games/$gameId/tokens'
      path: '/tokens'
      fullPath: '/games/$gameId/tokens'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdTokensImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdImport
    }
    '/_authenticated/_layout/teams/$groupId/billing': {
      id: '/_authenticated/_layout/teams/$groupId/billing'
      path: '/billing'
      fullPath: '/teams/$groupId/billing'
      preLoaderRoute: typeof AuthenticatedLayoutTeamsGroupIdBillingImport
      parentRoute: typeof AuthenticatedLayoutTeamsGroupIdImport
    }
    '/_authenticated/_layout/teams/$groupId/members': {
      id: '/_authenticated/_layout/teams/$groupId/members'
      path: '/members'
      fullPath: '/teams/$groupId/members'
      preLoaderRoute: typeof AuthenticatedLayoutTeamsGroupIdMembersImport
      parentRoute: typeof AuthenticatedLayoutTeamsGroupIdImport
    }
    '/_authenticated/_layout/teams/$groupId/settings': {
      id: '/_authenticated/_layout/teams/$groupId/settings'
      path: '/settings'
      fullPath: '/teams/$groupId/settings'
      preLoaderRoute: typeof AuthenticatedLayoutTeamsGroupIdSettingsImport
      parentRoute: typeof AuthenticatedLayoutTeamsGroupIdImport
    }
    '/_authenticated/_layout/games/$gameId/': {
      id: '/_authenticated/_layout/games/$gameId/'
      path: '/'
      fullPath: '/games/$gameId/'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdIndexImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdImport
    }
    '/_authenticated/_layout/teams/$groupId/': {
      id: '/_authenticated/_layout/teams/$groupId/'
      path: '/'
      fullPath: '/teams/$groupId/'
      preLoaderRoute: typeof AuthenticatedLayoutTeamsGroupIdIndexImport
      parentRoute: typeof AuthenticatedLayoutTeamsGroupIdImport
    }
    '/_authenticated/_layout/games/$gameId/namespaces/$': {
      id: '/_authenticated/_layout/games/$gameId/namespaces/$'
      path: '/namespaces/$'
      fullPath: '/games/$gameId/namespaces/$'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdNamespacesSplatImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdImport
    }
    '/_authenticated/_layout/games/$gameId/settings/tokens': {
      id: '/_authenticated/_layout/games/$gameId/settings/tokens'
      path: '/tokens'
      fullPath: '/games/$gameId/settings/tokens'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdSettingsTokensImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdSettingsImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId'
      path: '/games/$gameId/environments/$namespaceId'
      fullPath: '/games/$gameId/environments/$namespaceId'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
      parentRoute: typeof AuthenticatedLayoutImport
    }
    '/_authenticated/_layout/games/$gameId/settings/': {
      id: '/_authenticated/_layout/games/$gameId/settings/'
      path: '/'
      fullPath: '/games/$gameId/settings/'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdSettingsIndexImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdSettingsImport
    }
    '/_authenticated/_layout/teams/$groupId/settings/': {
      id: '/_authenticated/_layout/teams/$groupId/settings/'
      path: '/'
      fullPath: '/teams/$groupId/settings/'
      preLoaderRoute: typeof AuthenticatedLayoutTeamsGroupIdSettingsIndexImport
      parentRoute: typeof AuthenticatedLayoutTeamsGroupIdSettingsImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend'
      path: '/backend'
      fullPath: '/games/$gameId/environments/$namespaceId/backend'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/cdn': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/cdn'
      path: '/cdn'
      fullPath: '/games/$gameId/environments/$namespaceId/cdn'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdCdnImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies'
      path: '/lobbies'
      fullPath: '/games/$gameId/environments/$namespaceId/lobbies'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/matchmaker': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/matchmaker'
      path: '/matchmaker'
      fullPath: '/games/$gameId/environments/$namespaceId/matchmaker'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdMatchmakerImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers'
      path: '/servers'
      fullPath: '/games/$gameId/environments/$namespaceId/servers'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/tokens': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/tokens'
      path: '/tokens'
      fullPath: '/games/$gameId/environments/$namespaceId/tokens'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdTokensImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/versions': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/versions'
      path: '/versions'
      fullPath: '/games/$gameId/environments/$namespaceId/versions'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdVersionsImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/modules': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/modules'
      path: '/modules'
      fullPath: '/games/$gameId/environments/$namespaceId/modules'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdModulesLazyImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/'
      path: '/'
      fullPath: '/games/$gameId/environments/$namespaceId/'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdIndexImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/logs': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/logs'
      path: '/logs'
      fullPath: '/games/$gameId/environments/$namespaceId/backend/logs'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendLogsImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/variables': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/variables'
      path: '/variables'
      fullPath: '/games/$gameId/environments/$namespaceId/backend/variables'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendVariablesImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/logs': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/logs'
      path: '/logs'
      fullPath: '/games/$gameId/environments/$namespaceId/lobbies/logs'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesLogsImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/settings': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/settings'
      path: '/settings'
      fullPath: '/games/$gameId/environments/$namespaceId/lobbies/settings'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesSettingsImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/builds': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/builds'
      path: '/builds'
      fullPath: '/games/$gameId/environments/$namespaceId/servers/builds'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersBuildsImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/'
      path: '/'
      fullPath: '/games/$gameId/environments/$namespaceId/backend/'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendIndexImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/'
      path: '/'
      fullPath: '/games/$gameId/environments/$namespaceId/lobbies/'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesIndexImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesImport
    }
    '/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/': {
      id: '/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/'
      path: '/'
      fullPath: '/games/$gameId/environments/$namespaceId/servers/'
      preLoaderRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersIndexImport
      parentRoute: typeof AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedLayoutRoute: AuthenticatedLayoutRoute.addChildren({
      AuthenticatedLayoutMyProfileRoute:
        AuthenticatedLayoutMyProfileRoute.addChildren({
          AuthenticatedLayoutMyProfileFeaturesRoute,
          AuthenticatedLayoutMyProfileIndexRoute,
        }),
      AuthenticatedLayoutIndexRoute,
      AuthenticatedLayoutGamesGameIdRoute:
        AuthenticatedLayoutGamesGameIdRoute.addChildren({
          AuthenticatedLayoutGamesGameIdBillingRoute,
          AuthenticatedLayoutGamesGameIdSettingsRoute:
            AuthenticatedLayoutGamesGameIdSettingsRoute.addChildren({
              AuthenticatedLayoutGamesGameIdSettingsTokensRoute,
              AuthenticatedLayoutGamesGameIdSettingsIndexRoute,
            }),
          AuthenticatedLayoutGamesGameIdTokensRoute,
          AuthenticatedLayoutGamesGameIdIndexRoute,
          AuthenticatedLayoutGamesGameIdNamespacesSplatRoute,
        }),
      AuthenticatedLayoutTeamsGroupIdRoute:
        AuthenticatedLayoutTeamsGroupIdRoute.addChildren({
          AuthenticatedLayoutTeamsGroupIdBillingRoute,
          AuthenticatedLayoutTeamsGroupIdMembersRoute,
          AuthenticatedLayoutTeamsGroupIdSettingsRoute:
            AuthenticatedLayoutTeamsGroupIdSettingsRoute.addChildren({
              AuthenticatedLayoutTeamsGroupIdSettingsIndexRoute,
            }),
          AuthenticatedLayoutTeamsGroupIdIndexRoute,
        }),
      AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute:
        AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdRoute.addChildren({
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendRoute:
            AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendRoute.addChildren(
              {
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendLogsRoute,
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendVariablesRoute,
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdBackendIndexRoute,
              },
            ),
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdCdnRoute,
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesRoute:
            AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesRoute.addChildren(
              {
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesLogsRoute,
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesSettingsRoute,
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdLobbiesIndexRoute,
              },
            ),
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdMatchmakerRoute,
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersRoute:
            AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersRoute.addChildren(
              {
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersBuildsRoute,
                AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdServersIndexRoute,
              },
            ),
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdTokensRoute,
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdVersionsRoute,
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdModulesLazyRoute,
          AuthenticatedLayoutGamesGameIdEnvironmentsNamespaceIdIndexRoute,
        }),
    }),
    AuthenticatedBillingRoute,
    AuthenticatedAccessTokenTokenRoute,
    AuthenticatedInviteInviteCodeRoute,
    AuthenticatedDevicesLinkTokenRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_layout",
        "/_authenticated/billing",
        "/_authenticated/access-token/$token",
        "/_authenticated/invite/$inviteCode",
        "/_authenticated/devices/link/$token"
      ]
    },
    "/_authenticated/_layout": {
      "filePath": "_authenticated/_layout.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_layout/my-profile",
        "/_authenticated/_layout/",
        "/_authenticated/_layout/games/$gameId",
        "/_authenticated/_layout/teams/$groupId",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
      ]
    },
    "/_authenticated/billing": {
      "filePath": "_authenticated/billing.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_layout/my-profile": {
      "filePath": "_authenticated/_layout/my-profile.tsx",
      "parent": "/_authenticated/_layout",
      "children": [
        "/_authenticated/_layout/my-profile/features",
        "/_authenticated/_layout/my-profile/"
      ]
    },
    "/_authenticated/access-token/$token": {
      "filePath": "_authenticated/access-token.$token.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invite/$inviteCode": {
      "filePath": "_authenticated/invite.$inviteCode.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_layout/": {
      "filePath": "_authenticated/_layout/index.tsx",
      "parent": "/_authenticated/_layout"
    },
    "/_authenticated/_layout/games/$gameId": {
      "filePath": "_authenticated/_layout/games/$gameId.tsx",
      "parent": "/_authenticated/_layout",
      "children": [
        "/_authenticated/_layout/games/$gameId/billing",
        "/_authenticated/_layout/games/$gameId/settings",
        "/_authenticated/_layout/games/$gameId/tokens",
        "/_authenticated/_layout/games/$gameId/",
        "/_authenticated/_layout/games/$gameId/namespaces/$"
      ]
    },
    "/_authenticated/_layout/my-profile/features": {
      "filePath": "_authenticated/_layout/my-profile/features.tsx",
      "parent": "/_authenticated/_layout/my-profile"
    },
    "/_authenticated/_layout/teams/$groupId": {
      "filePath": "_authenticated/_layout/teams/$groupId.tsx",
      "parent": "/_authenticated/_layout",
      "children": [
        "/_authenticated/_layout/teams/$groupId/billing",
        "/_authenticated/_layout/teams/$groupId/members",
        "/_authenticated/_layout/teams/$groupId/settings",
        "/_authenticated/_layout/teams/$groupId/"
      ]
    },
    "/_authenticated/devices/link/$token": {
      "filePath": "_authenticated/devices.link.$token.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_layout/my-profile/": {
      "filePath": "_authenticated/_layout/my-profile/index.tsx",
      "parent": "/_authenticated/_layout/my-profile"
    },
    "/_authenticated/_layout/games/$gameId/billing": {
      "filePath": "_authenticated/_layout/games/$gameId/billing.tsx",
      "parent": "/_authenticated/_layout/games/$gameId"
    },
    "/_authenticated/_layout/games/$gameId/settings": {
      "filePath": "_authenticated/_layout/games/$gameId/settings.tsx",
      "parent": "/_authenticated/_layout/games/$gameId",
      "children": [
        "/_authenticated/_layout/games/$gameId/settings/tokens",
        "/_authenticated/_layout/games/$gameId/settings/"
      ]
    },
    "/_authenticated/_layout/games/$gameId/tokens": {
      "filePath": "_authenticated/_layout/games/$gameId/tokens.tsx",
      "parent": "/_authenticated/_layout/games/$gameId"
    },
    "/_authenticated/_layout/teams/$groupId/billing": {
      "filePath": "_authenticated/_layout/teams/$groupId/billing.tsx",
      "parent": "/_authenticated/_layout/teams/$groupId"
    },
    "/_authenticated/_layout/teams/$groupId/members": {
      "filePath": "_authenticated/_layout/teams/$groupId/members.tsx",
      "parent": "/_authenticated/_layout/teams/$groupId"
    },
    "/_authenticated/_layout/teams/$groupId/settings": {
      "filePath": "_authenticated/_layout/teams/$groupId/settings.tsx",
      "parent": "/_authenticated/_layout/teams/$groupId",
      "children": [
        "/_authenticated/_layout/teams/$groupId/settings/"
      ]
    },
    "/_authenticated/_layout/games/$gameId/": {
      "filePath": "_authenticated/_layout/games/$gameId/index.tsx",
      "parent": "/_authenticated/_layout/games/$gameId"
    },
    "/_authenticated/_layout/teams/$groupId/": {
      "filePath": "_authenticated/_layout/teams/$groupId/index.tsx",
      "parent": "/_authenticated/_layout/teams/$groupId"
    },
    "/_authenticated/_layout/games/$gameId/namespaces/$": {
      "filePath": "_authenticated/_layout/games/$gameId/namespaces/$.tsx",
      "parent": "/_authenticated/_layout/games/$gameId"
    },
    "/_authenticated/_layout/games/$gameId/settings/tokens": {
      "filePath": "_authenticated/_layout/games/$gameId/settings/tokens.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/settings"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId.tsx",
      "parent": "/_authenticated/_layout",
      "children": [
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/cdn",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/matchmaker",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/tokens",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/versions",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/modules",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/"
      ]
    },
    "/_authenticated/_layout/games/$gameId/settings/": {
      "filePath": "_authenticated/_layout/games/$gameId/settings/index.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/settings"
    },
    "/_authenticated/_layout/teams/$groupId/settings/": {
      "filePath": "_authenticated/_layout/teams/$groupId/settings/index.tsx",
      "parent": "/_authenticated/_layout/teams/$groupId/settings"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId",
      "children": [
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/logs",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/variables",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/"
      ]
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/cdn": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/cdn.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId",
      "children": [
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/logs",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/settings",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/"
      ]
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/matchmaker": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/matchmaker.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId",
      "children": [
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/builds",
        "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/"
      ]
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/tokens": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/tokens.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/versions": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/versions.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/modules": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/modules.lazy.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/index.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/logs": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/logs.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/variables": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/variables.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/logs": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/logs.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/settings": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/settings.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/builds": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/builds.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend/": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/backend/index.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/backend"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies/": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/lobbies/index.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/lobbies"
    },
    "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers/": {
      "filePath": "_authenticated/_layout/games/$gameId_/environments/$namespaceId/servers/index.tsx",
      "parent": "/_authenticated/_layout/games/$gameId/environments/$namespaceId/servers"
    }
  }
}
ROUTE_MANIFEST_END */
