name: license-check

on: [push]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check licenses
        run: |
          npx license-checker --onlyAllow 'Apache-2.0; BSD-2-Clause; BSD-3-Clause; ISC; MIT; MPL-2.0; CC0-1.0; CC-BY-4.0; Python-2.0; Unlicense; BlueOak-1.0.0; 0BSD; UNLICENSED; UNKNOWN'
